map/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

urlpatterns = [
    path('',views.Map, name = 'swk_map'),
]

mysite/urls.py
from django.contrib import admin
from django.conf.urls import url
from django.conf import settings
from django.views.generic import TemplateView
from django.urls import path, re_path, include
from django.conf.urls.static import static

# from geonode.urls import urlpatterns

from wagtail.admin import urls as wagtailadmin_urls
from wagtail.core import urls as wagtail_urls
from wagtail.documents import urls as wagtaildocs_urls



urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
    path('admin/', admin.site.urls),
    path('',include('swk.urls')),
    # path('',include('swkapi.urls')),
    path('map/',include('map.urls')),
    path('dashboard/',include('react_dashboard.urls')),
    # url(r'^swk/',include('swk.urls')),
    re_path(r'^cms/', include(wagtailadmin_urls)),
    re_path(r'^documents/', include(wagtaildocs_urls)),
    re_path(r'^pages/', include(wagtail_urls)),
    url(r'^report_builder/', include('report_builder.urls'))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

swk/swkapi/urls.py
from django.urls import include, path
from rest_framework import routers
from . import  views

router = routers.DefaultRouter()
router.register(r'trackid', views.tracksheetview)
router.register(r'bubblepopulation', views.populationView)

# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.
urlpatterns = [
    path('', include(router.urls)),
    # path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))
    ]

swk/urls.py
from django.urls import path
from django.conf.urls import url
from . import views
from django.conf import settings
from django.conf.urls.static import static

# from visits.models import Visits
urlpatterns = [
    path('',views.HomePage, name = 'homepage'),
    path('aboutus/', views.AboutUs, name = 'aboutus'),
    # path('formlayout/',views.formLayout,name='formlayout'),
    path('trackform/', views.TracksheetPage, name = "trackform"),
    path('trackform_det/',views.TrackformPageDetail, name ="trackform_det"),
    path('dutyentryform/', views.DutyEntryPage, name = "dutyentryform"),
    path('login/', views.user_login, name='login'),
    path("logout", views.logout_request, name="logout"),
    path('show/',views.show, name='show'),  
   
    path('edit/<int:id>', views.edit),  
    path('update/<int:id>', views.update),  
    path('delete/<int:id>', views.destroy),  
    # url(r'^download_data/(?P<year>\d{4})-(?P<month>\d{2})-(?P<day>\d{2})/$', views.download),
    # url(r'^download_data_zone/(?P<year>\d{4})-(?P<month>\d{2})-(?P<day>\d{2})&(?P<lane_name>\D+)/$', views.downloadzone),
    url(r'^download_data_zone/(?P<year>\d{4})-(?P<month>\d{2})-(?P<day>\d{2})to(?P<year1>\d{4})-(?P<month1>\d{2})-(?P<day1>\d{2})&(?P<zone_name>\D+)/$', views.downloadzone),
    path('report/',views.report,name='report'),
    path('faq/',views.FAQ, name = 'faq'),
    path('grievance/',views.Grievance, name = 'grievance'),
    path('rating/',views.RatingView, name = 'rating'),
    path('contact/',views.Contact, name = 'contact'),
    path('uploadimage/',views.uploadimage, name = 'uploadimage'),
    path('getdetails/',views.getdetails,name = 'getdetails'),
    path('audiogrievance/',views.audiogrievance, name = 'audiogrievance')
    # path('graphs/',views.Graphs, name = 'graphs'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

swk/models.py
from django.db import models
from django import forms
from django.forms import ModelForm
from datetime import datetime
from decimal import Decimal


from wagtail.core.models import Page
from django.utils.translation import gettext_lazy as _



class Document(models.Model):
    description = models.CharField(max_length=255, blank=True)
    document = models.FileField(upload_to='documents/')
    uploaded_at = models.DateTimeField(auto_now_add=True)

class DutyEntry(models.Model):
    lane_name = models.CharField(primary_key = True, max_length=200, blank = False)
    first_attendants_name = models.CharField(max_length=100)
    second_attendants_name = models.CharField(max_length=100)
    num_houses_lane = models.IntegerField()
   
    def __str__(self):
        return self.lane_name

class HomePage(Page):

    template = "HomePage.html"


class Zones(models.Model):
    id = models.CharField(primary_key=True, max_length=10)
    zone_name = models.CharField(max_length=100, blank=True, null=True)
    zone_id = models.CharField(max_length=10, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'zones'

class TracksheetModel(Page):

    template = "TracksheetForm.html"
class SwkAttendants(models.Model):
    attendant1 = models.CharField(max_length=50, blank=True, null=True)
    attendant2 = models.CharField(max_length=50, blank=True, null=True)
    supervisor = models.CharField(max_length=50, blank=True, null=True)
    zone_name = models.CharField(max_length=100, blank=True, null=True)
    zone_id = models.CharField(max_length=10, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'swk_attendants'

class Tracksheet(models.Model):
    # date =models.DateField()
    date =models.DateField(help_text=_('Enter Date'))
    lane_name = models.CharField(max_length=200, blank = False)
    # lane_name = models.ForeignKey(DutyEntry,default = 1, on_delete=models.SET_DEFAULT)
    num_attendants = models.CharField(default = 2,max_length= 10 )
    first_attendants_name = models.CharField(max_length=100)
    second_attendants_name = models.CharField(max_length=100)
    supervisor_name = models.CharField(max_length=100,default = 'Zaheer')
    num_houses_reached = models.IntegerField(default= 20,help_text=_('Enter Houses Reached'))
    num_houses_doing_segg = models.IntegerField()
    num_houses_giving_mixwaste = models.IntegerField()
    drywaste_bf = models.IntegerField()
    drywaste_af = models.IntegerField()
    wetwaste_bf = models.IntegerField()
    wetwaste_af = models.IntegerField()
    time_of_visit = models.CharField(max_length=100)
    track_id = models.AutoField(primary_key=True)
    rejected = models.IntegerField()
    reason_late_entry = models.CharField(blank=False,max_length=200,default="OnTime")
    zone_id=models.ForeignKey(Zones, on_delete=models.CASCADE)

    def __str__(self):
        return self.lane_name




class SwkTracksheetReport(models.Model):
    num_houses_reached = models.DecimalField(max_digits=11, decimal_places=3)
    num_houses_doing_segg = models.IntegerField()
    num_houses_giving_mixwaste = models.IntegerField()
    drywaste_bf = models.IntegerField()
    drywaste_af = models.IntegerField()
    wetwaste_bf = models.IntegerField()
    wetwaste_af = models.IntegerField()
    lane_name = models.CharField(max_length=200)
    num_attendants = models.IntegerField()
    first_attendants_name = models.CharField(max_length=100)
    second_attendants_name = models.CharField(max_length=100)
    time_of_visit = models.CharField(max_length=100)
    track_id = models.AutoField(primary_key=True)
    date = models.DateField()
    supervisor_name = models.CharField(max_length=100)
    num_houses = models.IntegerField(blank=True, null=True)
    rejected_total = models.IntegerField(blank=True, null=True)
    rejected_dry = models.IntegerField(blank=True, null=True)
    rejected_wet = models.IntegerField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'swk_tracksheet_report'

class Grievance(models.Model):
    name = models.CharField(max_length=100,help_text=_('Name'))
    email = models.EmailField(blank=True)
    mobile = models.CharField(max_length=15,blank=True, null=True)
    selectzones = models.CharField(max_length=100)
    selectlanes = models.CharField(max_length=100)
    # audio_src = models.CharField(max_length=100)
    audio_src = models.CharField(max_length=100,null=True, default=None, blank=True)
    # img_src =  models.CharField(max_length=100)
    img_src =  models.CharField(max_length=100,null=True, default=None, blank=True)
    # grievance = models.TextField(blank=False, null=False)
    grievance = models.TextField(null=True, default=None, blank=True),
    uploaded_at = models.DateTimeField(auto_now_add=True)
    grievance_no = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'swk_grievance'

class Rating(models.Model):
    name = models.CharField(max_length=100)
    mobile = models.CharField(null=True,max_length=10)
    email = models.CharField(max_length=100,null=True)
    service_swk = models.IntegerField(default='yes')
    timing_swk = models.IntegerField()
    mobile_swk = models.IntegerField()
    compost_kit_garden = models.IntegerField()
    communicate_swk = models.IntegerField()
    solid_waste_man = models.IntegerField()
    service_workers = models.IntegerField()
    segregation = models.IntegerField()
    recycle_process = models.IntegerField()
    awareness = models.IntegerField()
    role = models.CharField(max_length=10)
    class Meta:
        managed = False
        db_table = 'swk_rating'
        
class SwkBubblePopulation(models.Model):
    zone_id = models.CharField(max_length=50, blank=True, null=True)
    bubble_id = models.IntegerField(blank=True, null=True)
    spot_id = models.IntegerField(blank=True, null=True)
    bubble_population = models.IntegerField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'swk_bubble_population'

class UploadPictureModel(models.Model):
    picture = models.ImageField(upload_to='Images/', blank=True, null=True)
    name = models.CharField(max_length=100, blank=True, null=True)
    date = models.DateField(null=True, blank=True, default=datetime.now)

class SupervisorsList(models.Model):
    
    supervisor_names = models.CharField(max_length=100, blank=True, null=True)
    supervisor_email = models.CharField(max_length=100,null=True, blank=True)
    zone_id = models.CharField(max_length=100,null=True, blank=True)
    class Meta:
        managed = False
        db_table = 'swk_zone_supervisors'

swk/swkapi/models.py
from django.db import models
from swk.models import Tracksheet
# Create your models here.

swk/swkapi/views.py
from django.shortcuts import render

# Create your views here.
from rest_framework import viewsets

from .serializers import newTracksheet,populationSerializer
from swk.models import Tracksheet,SwkBubblePopulation


class tracksheetview(viewsets.ModelViewSet):
    queryset = Tracksheet.objects.all().order_by('track_id')
    serializer_class = newTracksheet
    # def get_queryset(self,*args, **kwargs):
    #             # selectedTab = self.kwargs.get('tab', None)
    #             queryset = Tracksheet.objects.all().order_by('num_houses_giving_mixwaste')
    #             return queryset

class populationView(viewsets.ModelViewSet):
    queryset = SwkBubblePopulation.objects.all()
    serializer_class = populationSerializer

swk/templates/HomePage.html
{% extends 'new.html' %} {% load static %}
{% load i18n %}

<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
{% block extra_css%}
<style>
    .centered {
        position: absolute;
        /* top: 40%; */
        left: 50%;
        transform: translate(-50%, -50%);
        color: aliceblue;
    }
</style>

{% endblock %} {% block content %}


<section id="hero">
    <div class="hero-container">
        <h1>{% trans "Swachh Worli Koliwada" %}</h1>
        
        <h2>{% trans "A Project by Stree Mukti Sanghatana, sponsored by IDFC FIRST Bank" %}</h2>
        <!-- <a href="#about" class="btn-get-started scrollto">Get Started</a> -->
    </div>
   
</section>
{% if messages %}
<ul class="messages">
    {% for message in messages %}

    <div class="alert alert-success alert-dismissible fade show" role="alert">
        {{message}}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
    </div>

    {% endfor %}
</ul>
{% endif %}
</div>
<script src="http://code.jquery.com/jquery-1.11.0.min.js"></script>

<script>
</script>

{% endblock %}

swk/templates/TracksheetForm.html
{% extends 'new.html' %} {% load crispy_forms_tags %} {% block content %} {% block extra_css %}
{% load i18n %}
{% load l10n %}

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

<style>
    .form-row {
        margin: 50px;
    }
    
    table {
        padding: 10px;
    }
    #formdiv{
        float: left;  

    }
    #picimage{
       padding-left: 0px; 
    }
</style>
{% endblock %}
<div class="container mb-7" style="margin-top: 10px; ">
   <br>
    <h2>{% trans "Houses providing segregated Waste "%}</h2><hr><br>
    {% if messages %}
<ul class="messages">
    {% for message in messages %}

    <div class="alert alert-success alert-dismissible fade show" role="alert">
        {{message}}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
    </div>

    {% endfor %}
</ul>
{% endif %}
<div id = "formdiv">
    <form method="post" data-url="{{ request.build_absolute_uri|safe }}"  class="form-group" style="text-align:left;">
        {% csrf_token %}
        <table style="margin-right: 10px";>{{ form.as_table }} </table> 
        <br>
    <centre><button type="submit" style="align-items: center;" class="btn btn-primary">{% trans "Submit" %}</button></centre>
    
</form>
</div>
    <br>
    <!-- <form method="post" data-url="{{ request.build_absolute_uri|safe }}"  class="form-group" style="text-align:left;">
        {% csrf_token %}
        <table style="margin-right: 10px";>{{ form1.as_table }} </table> 
        
         {{ form1.picture.url}}
        <br>
    </form> -->
    <div id = "picimage" >
    {% for i in diary %}
        <!-- {{ i.date}} -->
        <img id ='testimg' src ='{{ i.picture.url }}' style="height:400px; width:550px; border:2px solid #555;"/>
    {% endfor %}
    </div>
    <!-- <div id="pic">
        {% for i in diary %}
            {{ i.picture}}
            <img src= "{{ i.picture.url }}" alt="No image uploaded" style="height:400px; width:550px; border:2px solid #555;"/></br>
           
        {% endfor %}
        
    </div> -->

   <div style="height: 200px;"></div>
</div>

<div>
    <!-- {{ form.errors }}
  {{ form.non_field_errors }} -->

</div>
 {% endblock %}

{% block extra_javascript %}
<script>
    $(function() {
        var $docName = $('#id_lane_name').val();
        console.log($docName)
        
        $("#id_lane_name").on('change', function() {
            var val = $("#id_lane_name").val();

            var $name = {
                'name': $(this).val()
            }
            console.log("name is ",$name)
            var $endpoint = window.location.href // or localhost/interface
            $.ajax({
                method: "GET",
                url: $endpoint,
                data: $name,
                success: handleFormSuccess,
                error: handleFormError,
            })
        })
        $("#id_date").on('change', function() {
            var val1 = $("#id_date").val();

            var $name1 = {
                'name1': $(this).val()
            }
            console.log("name1 is ",$name1)
            var $endpoint = window.location.href // or localhost/interface
            $.ajax({
                method: "GET",
                url: $endpoint,
                data: $name1,
                success: handleFormSuccess1,
                error: handleFormError1,
            })
        })

        function handleFormSuccess(data) {
            console.log(data.zone_id);
            $("#id_zone_id_id").val(data.zone_id);
            $("#id_first_attendants_name").val(data.attendant1);
            $("#id_second_attendants_name").val(data.attendant2);
            $("#id_supervisor_name").val(data.supervisor);
           
            // $("#id_pic").val(data.picture.url);
        }
        function handleFormSuccess1(data) {
            
            console.log(data.picture);
                   
            // $("#id_picture").val(data.picture);
            // $("#id_picture").val(data.picture);
            icon_url = '{{ media_url}}' 
            console.log('"'+icon_url+data.picture+'"');
            // $('#id_picture').html('<img src='+icon_url+data.picture+ '" />');
            $('#testimg').empty();
            $('#testimg').attr('src',icon_url+data.picture);
            
             //$('#id_picture').html('Hi');
            //  $('#id_picture').
            // $("#id_picture").attr("src",data.picture);
            // $('#id_picture').show();
        }

        function handleFormError(jqXHR, textStatus, errorThrown) {
            console.log(jqXHR)
            console.log(textStatus)
            console.log(errorThrown)
        }
        function handleFormError1(jqXHR, textStatus, errorThrown) {
            console.log(jqXHR)
            console.log(textStatus)
            console.log(errorThrown)
        }
    })
</script>

{% endblock %}

swk/templates/aboutus.html
{% extends 'new.html' %} 
{% load i18n %}
{% block content %}{% block extra_css %}


{% endblock %}

    <br>
    <div class="container mb-7" >
        <h2>{% trans "About Swachh Worli Koliwada" %}</h2>
        <br>
    </div>      
    <div class="container"style="overflow:auto;"  >
        <div class="row" >
            <div class="col-sm-8" >
                <h3>{% trans "Background" %}</h3>
                <hr>
                <h5>
                    <p style="text-align:justify">{% blocktrans %}IDFC FIRST Bank in collaboration with Municipal Corporation of Greater Mumbai (MCGM) and Stree Mukti Sanghatana spearheaded Swachh Worli Koliwada project with an aim to create awareness and bring about a behavioural change in the community on solid waste management practices and adoption of waste segregation at source. The project plans to drive this change through a participatory process within the Worli Koliwada community. {% endblocktrans %}</p>
                    <p style="text-align:justify">{% blocktrans %}Swachh Worli Koliwada project aims at building a zero waste neighbourhood with self-sustainable zones that are equipped to manage solid waste they generate, with a model where community participation will be a key at every stage, ensuring sustainability of this program. {% endblocktrans %}</p>
                </h5>
                    
                <br>
                <a href = "https://www.idfcfirstbank.com"><h3>{% trans "About IDFC FIRST Bank" %}</h3></a>
                <hr>
                <h5>
                    <p style="text-align:justify;">{% blocktrans %}IDFC FIRST Bank was founded by the merger of IDFC Bank and Capital First in December 2018. The Bank provides a range of financial solutions to individuals, small businesses and corporates. The Bank offers savings and current accounts, NRI accounts, salary accounts, demat accounts, fixed and recurring deposits, home and personal loans, two-wheeler loans, consumer durable loans, small business loans, forex products, payment solutions and wealth management services. IDFC FIRST Bank has a nationwide presence and operates in the Retail Banking, Wholesale Banking and other Banking segments.{% endblocktrans %}
                    </p>
                </h5>
                <br>

                <a href ="https://portal.mcgm.gov.in/"><h3>{% trans "About Municipal Corporation of Greater Mumbai " %}</h3></a>
                <hr>
                <h5>
                    <p style="text-align:justify">{% blocktrans %}The Municipal Corporation of Greater Mumbai (MCGM) formerly and commonly known as the Bombay Municipal Corporation (BMC) is the governing civic body of Mumbai, the capital city of Maharashtra.  MCGM is responsible for the civic infrastructure and administration of the city and some suburbs.Brihanmumbai Mahanagarpalika covers an area of 480.24 sq.kms with a population of 1,19,14,378 as per the census of 2001. The metropolis accounts major portion of India's international trade and government revenue, from being one of the foremost centers of education, science and technological research and advancement. {% endblocktrans %}
                </h5>
                </p>
                <br>
               
                <a href ="https://streemuktisanghatana.org/"><h3>{% trans "About Stree Mukti Sangathana(SMS)" %}</h3></a>
                <hr>
                <h5>
                    <p style="text-align:justify">{% blocktrans %}Stree Mukti Sanghatana established in 1975 is a non-profit organisation and strives to create a gender just world by improving the lives of women through education, awareness, healthcare, and opportunities for livelihood. Its vision is eradication of poverty and violence, and creation of a conducive atmosphere for equality.  It engages in the process of dialogues and reformation through various activities like Theatre, in-house monthly publication “Prerak Lalkari”,  Family Counselling centres, Adolescent sensitization program, creating sustainable livelihood programmes etc.  {% endblocktrans %}</p>
                    <p style="text-align:justify">{% blocktrans %}Since 1999 SMS has been working for the cause of women waste pickers and offering solutions for Solid Waste Management. SMS is registered under Bombay Public Trusts Act and Societies registration act and has 80-G and 12 A certificates under the Income Tax Act, 1961. {% endblocktrans %}</p>
                </h5>
                </p>
                <br>

                              
                <a href = "https://communitygis.net/"><h3>{% trans "About Community GIS" %}</h3></a>
                <hr>
                <h5>
                    <p style="text-align:justify">
                        {% blocktrans %}Communitygis is a Free and Open Source platform for community ownership of data and code for geographic data. 
                        Technically communityGIS is a platform for a spatial data infrastructure. 
                        This consists of an application  (with license GPLv3 ) frontend as GUI  using python Django and Javascripts while the backend is geonode the code is available at github .
                        This platform can be used with modifications for other themes. The preliminary instructions to install and use  will be made available soon .
                        This has been developed by teams from makerghat and  CTARA IIT Bombay .{% endblocktrans %}
                    </p>
                </h5>
            </div>
        </div>
    </div>
    <br>
        
{% endblock %}

swk/templates/adminlogin.html
{% extends 'new.html' %} {% load static%}
{% load i18n %}

<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<title>Registration</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href=""> {% block extra_css %}
<style>
    .myform {
        margin: 0px 0px;
    }
    
    .card-panel {
        margin-bottom: 0px;
    }
</style>
{% endblock %} {% block content %} {% if messages %}
<ul class="messages">
    {% for message in messages %}

    <div class="alert alert-success alert-dismissible fade show" role="alert">
        {{message}}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
    </div>

    {% endfor %}
</ul>
{% endif %}


<div class='container' style="text-align: center; margin-bottom: 190px;">
    <form action="{% url 'login' %}" method="POST" class="form-group">
        {% csrf_token %}
        <div class="myform"><br><br><br><br>
            <h3>{% trans "SWK Portal Login" %}</h3>

            <div class="card-panel">
                <input type="text" class="form-control" name="username" aria-describedby="emailHelp" placeholder={% trans "EnterUsername" %} id="name">
            </div>
            <br>
            <div class="card-panel">
                <input type="password" class="form-control" name="password" id="exampleInputPassword1" placeholder={% trans "Password" %}>
            </div><br><br>

            <button type="submit" class="btn btn-success btn-lg">{% trans "Login" %} </button>
        </div>

    </form>
    <br>
</div>


{% endblock %}

swk/templates/edit.html
{% extends 'new.html' %} {% load static%} {% block content %}
{% load i18n %}

<div class="container mb-5 text-center">

    <form method="POST" class="post-form" action="/update/{{data.track_id}}" style="margin-top: 80px;">
        {% csrf_token %}


        <div>
            <label class="col-sm-1 col-form-label"></label>
            <div>
                <h3>{% trans "Update Details" %}</h3>
            </div>
        </div>
        <div>
            <label> {% trans "Track ID" %}:</label>
            <div>
                <input type="text" name="id" id="id_track_id" required value="{{ data.track_id }}" disabled =True />
            </div>
        </div>
        <div>
            <label> {% trans "Houses Reached:" %}</label>
            <div>
                <input type="text" name="num_houses_reached" id="id_num_houses_reached" required value="{{ data.num_houses_reached }}" />
            </div>
        </div>
        <div>
            <label> {% trans "Houses Doing Seggregation:" %}</label>
            <div>
                <input type="text" name="num_houses_doing_segg" id="id_num_houses_doing_segg" required value="{{ data.num_houses_doing_segg }}" />
            </div>
        </div>
        <div>
            <label> {% trans "Houses Giving Mixed Wasted:" %}</label>
            <div>
                <input type="text" name="num_houses_giving_mixwaste" id="id_num_houses_giving_mixwaste" required value="{{ data.num_houses_giving_mixwaste }}" />
            </div>
        </div>
        <div>
            <label>{% trans "Dry Waste BF:" %}</label>
            <div>
                <input type="text" name="drywaste_bf" id="id_drywaste_bf" required value="{{ data.drywaste_bf }}" />
            </div>
        </div>
        <div>
            <label>{% trans "Dry Waste AF:" %}</label>
            <div>
                <input type="text" name="drywaste_af" id="id_drywaste_af" required value="{{ data.drywaste_af }}" />
            </div>
        </div>
        <div>
            <label>{% trans "Wet Waste BF:" %}</label>
            <div>
                <input type="text" name="wetwaste_bf" id="id_wetwaste_bf" required value="{{ data.wetwaste_bf }}" />
            </div>
        </div>
        <div>
            <label>{% trans "Wet Waste AF:" %}</label>
            <div>
                <input type="text" name="wetwaste_af" id="id_wetwaste_af" required value="{{ data.wetwaste_af }}" />
            </div>
        </div>
        <div>
            <label>{% trans "Zone Name:" %}</label>
            <div>
                <input type="text" name="lane_name" id="id_lane_name" required value="{{ data.lane_name }}" />
            </div>
        </div>
        
        <div>
            <label>{% trans "Date:" %}</label>
            <div>
                <input type="text" name="date" id="id_date" required value="{{ data.date|date:'Y-m-d' }}" />
            </div>
        </div>
        <div>
            <label>{% trans "Supervisor Name:" %}</label>
            <div>
                <input type="text" name="supervisor_name" id="id_supervisor_name" required value="{{ data.supervisor_name }}" />
            </div>
        </div>
        <div>
            <label>{% trans "Rejected:" %}</label>
            <div>
                <input type="text" name="rejected" id="id_rejected" required value="{{ data.rejected }}" />
            </div>
        </div>
        <div style="display:none;">
            <label>{% trans "Zone ID:" %}</label>
            <div>
                <input type="text" name="zone_id_id" id="id_zone_id_id" required value="{{ data.zone_id_id }}" />
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-1 col-form-label"></label>
            <div class="col-sm-4">
                <button type="submit" class="btn btn-success">{% trans "Update" %}</button>
            </div>
        </div>
    </form>
</div>
<script>
    // console.log("{{ data.zone_id_id }}")
</script>
{% endblock %}

swk/templates/graphs.html
{% extends 'new.html' %} 
{% load i18n %}
{% block content %}{% block extra_css %}


{% endblock %}
{% autoescape off %}
{{ plot_div }}
{% endautoescape %}
<hr>
<hr>

{% autoescape off %}
{{ plot_div1 }}
{% endautoescape %}
<hr>

{% autoescape off %}
{{ plot_div2 }}
{% endautoescape %}

{% endblock %}